### ISSUE TITLE
Question about stage 3

### ISSUE THREAD

**Issue by MooreManor** [chaneyddtt/Coarse-to-fine-3D-Animal#6]
@chaneyddtt  Hello! Coarse-to-fine-3D-Animal is a nice work. I have a few questions about stage 3 training.

1. Did you try to add supervision on coarse-network output (i.e. SMAL parameters) at stage 3? 
2. Will stage 3 supervision only on non-parametric representations worsen predictions of parametric representation?
3. Why [feat_multiscale](https://github.com/chaneyddtt/Coarse-to-fine-3D-Animal/blob/b3f9b1031b5761838c94ca091095636101747fd9/model/mesh_graph_hg.py#L83) used a detached copy here at stage 3? Shouldn't the graphnet update the multiscale backbone here?

**Comment by chaneyddtt** [comment]
Hi @MooreManor, sorry for the late reply and thanks for your interests. 
1. yes, we have the supervision for the coarse output at stage 3
2. yes, the results will become worse if we only apply supervision on the non-parametric prediction.
3. Firstly, the feature can be optimised with the coarse output supervision. Secondly, the gradient from the fine stage can still flow back to the feature since the input of the refine stage is from the output of the coarse stage.

**Comment by MooreManor** [comment]
@chaneyddtt Thanks for your reply! I also have a question about training on stages 1 and 2. When training these two stages,
 do you train the model to converge fully? Or for stage 1 just a good initialization that can give a coarse output okay, and for stage 2 also a good initialized network parameter?

**Comment by MooreManor** [comment]
@chaneyddtt For the mesh sampling operation, do you use [coma](https://github.com/anuragranj/coma)?

**Comment by chaneyddtt** [comment]
Hi @MooreManor,
1. I generally train the first stage fully, and the second stage is trained just for a good initialisation (very few epochs).  This is because that we did not add any shape prior in the second stage, which will results in invalid shapes if trained for too long.
2. Yes, I use coma for mesh downsampling

**Comment by MooreManor** [comment]
@chaneyddtt 
Thanks! I am clear :)
